"""
Generation source; defines the order that items appear in the tracker
"""
from ..item import item_names, item_tables
from dataclasses import dataclass


class Spacer:
    pass

@dataclass
class FillerCounter:
    item_name: str


class Upgradeable:
    def __init__(
        self,
        parent_items: str | list[str] | None | Spacer,
        child_items: list[str] = (),
        classname: str | None = None,
    ) -> None:
        self.parent_items = (
            () if parent_items is None
            else (parent_items,) if isinstance(parent_items, str) or isinstance(parent_items, Spacer)
            else tuple(parent_items)
        )
        self.child_items = child_items
        self.classname = (
            self.parent_items[0].lower().replace("'", '').replace(' ', '-')
            if classname is None
            else classname
        )


@dataclass
class SectionBreak:
    section_id: str

@dataclass
class SubSection:
    name: str

TrackerElements = str | FillerCounter | Upgradeable | SectionBreak | SubSection | Spacer


FILLER_ITEMS: list[TrackerElements] = [
    FillerCounter(item_names.STARTING_MINERALS),
    FillerCounter(item_names.STARTING_VESPENE),
    FillerCounter(item_names.STARTING_SUPPLY),
    FillerCounter(item_names.MAX_SUPPLY),
    FillerCounter(item_names.REDUCED_MAX_SUPPLY),
    FillerCounter(item_names.BUILDING_CONSTRUCTION_SPEED),
    FillerCounter(item_names.SHIELD_REGENERATION),
    FillerCounter(item_names.UPGRADE_RESEARCH_SPEED),
    FillerCounter(item_names.UPGRADE_RESEARCH_COST),
]

TERRAN_ITEMS: list[TrackerElements] = [
    SubSection("Barracks"),
    Upgradeable(item_names.MARINE, [
        item_names.MARINE_COMBAT_SHIELD,
        item_names.MARINE_LASER_TARGETING_SYSTEM,
        item_names.MARINE_MAGRAIL_MUNITIONS,
        item_names.MARINE_OPTIMIZED_LOGISTICS,
        item_names.MARINE_PROGRESSIVE_STIMPACK,
    ]),
    Upgradeable(item_names.MEDIC, [
        item_names.MEDIC_ADAPTIVE_MEDPACKS,
        item_names.MEDIC_ADVANCED_MEDIC_FACILITIES,
        item_names.MEDIC_NANO_PROJECTOR,
        item_names.MEDIC_OPTICAL_FLARE,
        item_names.MEDIC_RESOURCE_EFFICIENCY,
        item_names.MEDIC_RESTORATION,
        item_names.MEDIC_STABILIZER_MEDPACKS,
    ]),
    Upgradeable(item_names.FIREBAT, [
        item_names.FIREBAT_INCINERATOR_GAUNTLETS,
        item_names.FIREBAT_INFERNAL_PRE_IGNITER,
        item_names.FIREBAT_JUGGERNAUT_PLATING,
        item_names.FIREBAT_KINETIC_FOAM,
        item_names.FIREBAT_NANO_PROJECTORS,
        item_names.FIREBAT_PROGRESSIVE_STIMPACK,
        item_names.FIREBAT_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.MARAUDER, [
        item_names.MARAUDER_CONCUSSIVE_SHELLS,
        item_names.MARAUDER_INTERNAL_TECH_MODULE,
        item_names.MARAUDER_JUGGERNAUT_PLATING,
        item_names.MARAUDER_KINETIC_FOAM,
        item_names.MARAUDER_LASER_TARGETING_SYSTEM,
        item_names.MARAUDER_MAGRAIL_MUNITIONS,
        item_names.MARAUDER_PROGRESSIVE_STIMPACK,
    ]),
    Upgradeable(item_names.REAPER, [
        item_names.REAPER_ADVANCED_CLOAKING_FIELD,
        item_names.REAPER_BALLISTIC_FLIGHTSUIT,
        item_names.REAPER_COMBAT_DRUGS,
        item_names.REAPER_G4_CLUSTERBOMB,
        item_names.REAPER_JET_PACK_OVERDRIVE,
        item_names.REAPER_LASER_TARGETING_SYSTEM,
        item_names.REAPER_PROGRESSIVE_STIMPACK,
        item_names.REAPER_RESOURCE_EFFICIENCY,
        item_names.REAPER_SPIDER_MINES,
        item_names.REAPER_U238_ROUNDS,
    ]),
    Upgradeable(item_names.GHOST, [
        item_names.GHOST_BARGAIN_BIN_PRICES,
        item_names.GHOST_CRIUS_SUIT,
        item_names.GHOST_EMP_ROUNDS,
        item_names.GHOST_LOCKDOWN,
        item_names.GHOST_OCULAR_IMPLANTS,
        item_names.GHOST_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.SPECTRE, [
        item_names.SPECTRE_BARGAIN_BIN_PRICES,
        item_names.SPECTRE_IMPALER_ROUNDS,
        item_names.SPECTRE_NYX_CLASS_CLOAKING_MODULE,
        item_names.SPECTRE_PSIONIC_LASH,
        item_names.SPECTRE_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.HERC, [
        item_names.HERC_GRAPPLE_PULL,
        item_names.HERC_JUGGERNAUT_PLATING,
        item_names.HERC_KINETIC_FOAM,
        item_names.HERC_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.DOMINION_TROOPER, [
        item_names.DOMINION_TROOPER_ADVANCED_ALLOYS,
        item_names.DOMINION_TROOPER_B2_HIGH_CAL_LMG,
        item_names.DOMINION_TROOPER_CPO7_SALAMANDER_FLAMETHROWER,
        item_names.DOMINION_TROOPER_HAILSTORM_LAUNCHER,
        item_names.DOMINION_TROOPER_OPTIMIZED_LOGISTICS,
    ]),
    SubSection("Factory"),
    Upgradeable(item_names.HELLION, [
        item_names.HELLION_HELLBAT,
        item_names.HELLION_INFERNAL_PLATING,
        item_names.HELLION_JUMP_JETS,
        item_names.HELLION_OPTIMIZED_LOGISTICS,
        item_names.HELLION_PROGRESSIVE_STIMPACK,
        item_names.HELLION_SMART_SERVOS,
        item_names.HELLION_THERMITE_FILAMENTS,
        item_names.HELLION_TWIN_LINKED_FLAMETHROWER,
    ]),
    Upgradeable(item_names.VULTURE, [
        item_names.VULTURE_AUTO_LAUNCHERS,
        item_names.VULTURE_ION_THRUSTERS,
        item_names.VULTURE_JERRYRIGGED_PATCHUP,
        item_names.VULTURE_PROGRESSIVE_REPLENISHABLE_MAGAZINE,
    ]),
    Upgradeable(item_names.GOLIATH, [
        item_names.GOLIATH_ARES_CLASS_TARGETING_SYSTEM,
        item_names.GOLIATH_INTERNAL_TECH_MODULE,
        item_names.GOLIATH_JUMP_JETS,
        item_names.GOLIATH_MULTI_LOCK_WEAPONS_SYSTEM,
        item_names.GOLIATH_OPTIMIZED_LOGISTICS,
        item_names.GOLIATH_RESOURCE_EFFICIENCY,
        item_names.GOLIATH_SHAPED_HULL,
    ]),
    Upgradeable(item_names.DIAMONDBACK, [
        item_names.DIAMONDBACK_BURST_CAPACITORS,
        item_names.DIAMONDBACK_HYPERFLUXOR,
        item_names.DIAMONDBACK_MAGLEV_PROPULSION,
        item_names.DIAMONDBACK_PROGRESSIVE_TRI_LITHIUM_POWER_CELL,
        item_names.DIAMONDBACK_RESOURCE_EFFICIENCY,
        item_names.DIAMONDBACK_SHAPED_HULL,
    ]),
    Upgradeable(item_names.SIEGE_TANK, [
        item_names.SIEGE_TANK_ADVANCED_SIEGE_TECH,
        item_names.SIEGE_TANK_ALLTERRAIN_TREADS,
        item_names.SIEGE_TANK_GRADUATING_RANGE,
        item_names.SIEGE_TANK_INTERNAL_TECH_MODULE,
        item_names.SIEGE_TANK_JUMP_JETS,
        item_names.SIEGE_TANK_LASER_TARGETING_SYSTEM,
        item_names.SIEGE_TANK_MAELSTROM_ROUNDS,
        item_names.SIEGE_TANK_PROGRESSIVE_TRANSPORT_HOOK,
        item_names.SIEGE_TANK_RESOURCE_EFFICIENCY,
        item_names.SIEGE_TANK_SHAPED_BLAST,
        item_names.SIEGE_TANK_SHAPED_HULL,
        item_names.SIEGE_TANK_SMART_SERVOS,
        item_names.SIEGE_TANK_SPIDER_MINES,
    ]),
    Upgradeable(item_names.THOR, [
        item_names.THOR_330MM_BARRAGE_CANNON,
        item_names.THOR_BUTTON_WITH_A_SKULL_ON_IT,
        item_names.THOR_LARGE_SCALE_FIELD_CONSTRUCTION,
        item_names.THOR_LASER_TARGETING_SYSTEM,
        item_names.THOR_PROGRESSIVE_HIGH_IMPACT_PAYLOAD,
        item_names.THOR_PROGRESSIVE_IMMORTALITY_PROTOCOL,
        item_names.THOR_RAPID_RELOAD,
    ]),
    Upgradeable(item_names.PREDATOR, [
        item_names.PREDATOR_ADAPTIVE_DEFENSES,
        item_names.PREDATOR_CHARGE,
        item_names.PREDATOR_CLOAK,
        item_names.PREDATOR_RESOURCE_EFFICIENCY,
        item_names.PREDATOR_VESPENE_SYNTHESIS,
    ]),
    Upgradeable(item_names.WIDOW_MINE, [
        item_names.WIDOW_MINE_BLACK_MARKET_LAUNCHERS,
        item_names.WIDOW_MINE_CONCEALMENT,
        item_names.WIDOW_MINE_DEMOLITION_PAYLOAD,
        item_names.WIDOW_MINE_DRILLING_CLAWS,
        item_names.WIDOW_MINE_EXECUTIONER_MISSILES,
        item_names.WIDOW_MINE_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.CYCLONE, [
        item_names.CYCLONE_INTERNAL_TECH_MODULE,
        item_names.CYCLONE_MAG_FIELD_ACCELERATORS,
        item_names.CYCLONE_MAG_FIELD_LAUNCHERS,
        item_names.CYCLONE_RAPID_FIRE_LAUNCHERS,
        item_names.CYCLONE_RESOURCE_EFFICIENCY,
        item_names.CYCLONE_TARGETING_OPTICS,
    ]),
    Upgradeable(item_names.WARHOUND, [
        item_names.WARHOUND_AXIOM_PLATING,
        item_names.WARHOUND_DEPLOY_TURRET,
        item_names.WARHOUND_RESOURCE_EFFICIENCY,
    ]),
    SubSection("Starport"),
    Upgradeable(item_names.MEDIVAC, [
        item_names.MEDIVAC_ADVANCED_CLOAKING_FIELD,
        item_names.MEDIVAC_ADVANCED_HEALING_AI,
        item_names.MEDIVAC_AFTERBURNERS,
        item_names.MEDIVAC_EXPANDED_HULL,
        item_names.MEDIVAC_RAPID_DEPLOYMENT_TUBE,
        item_names.MEDIVAC_RAPID_REIGNITION_SYSTEMS,
        item_names.MEDIVAC_RESOURCE_EFFICIENCY,
        item_names.MEDIVAC_SCATTER_VEIL,
    ]),
    Upgradeable(item_names.WRAITH, [
        item_names.WRAITH_ADVANCED_LASER_TECHNOLOGY,
        item_names.WRAITH_DISPLACEMENT_FIELD,
        item_names.WRAITH_INTERNAL_TECH_MODULE,
        item_names.WRAITH_PROGRESSIVE_TOMAHAWK_POWER_CELLS,
        item_names.WRAITH_RESOURCE_EFFICIENCY,
        item_names.WRAITH_TRIGGER_OVERRIDE,
    ]),
    Upgradeable(item_names.VIKING, [
        item_names.VIKING_AESIR_TURBINES,
        item_names.VIKING_ANTI_MECHANICAL_MUNITION,
        item_names.VIKING_PHOBOS_CLASS_WEAPONS_SYSTEM,
        item_names.VIKING_RIPWAVE_MISSILES,
        item_names.VIKING_SHREDDER_ROUNDS,
        item_names.VIKING_SMART_SERVOS,
        item_names.VIKING_WILD_MISSILES,
    ]),
    Upgradeable(item_names.BANSHEE, [
        item_names.BANSHEE_ADVANCED_TARGETING_OPTICS,
        item_names.BANSHEE_DISTORTION_BLASTERS,
        item_names.BANSHEE_HYPERFLIGHT_ROTORS,
        item_names.BANSHEE_INTERNAL_TECH_MODULE,
        item_names.BANSHEE_LASER_TARGETING_SYSTEM,
        item_names.BANSHEE_PROGRESSIVE_CROSS_SPECTRUM_DAMPENERS,
        item_names.BANSHEE_ROCKET_BARRAGE,
        item_names.BANSHEE_SHAPED_HULL,
        item_names.BANSHEE_SHOCKWAVE_MISSILE_BATTERY,
    ]),
    Upgradeable(item_names.LIBERATOR, [
        item_names.LIBERATOR_ADVANCED_BALLISTICS,
        item_names.LIBERATOR_CLOAK,
        item_names.LIBERATOR_GUERILLA_MISSILES,
        item_names.LIBERATOR_LASER_TARGETING_SYSTEM,
        item_names.LIBERATOR_OPTIMIZED_LOGISTICS,
        item_names.LIBERATOR_RAID_ARTILLERY,
        item_names.LIBERATOR_RESOURCE_EFFICIENCY,
        item_names.LIBERATOR_SMART_SERVOS,
        item_names.LIBERATOR_UED_MISSILE_TECHNOLOGY,
    ]),
    Upgradeable(item_names.VALKYRIE, [
        item_names.VALKYRIE_AFTERBURNERS,
        item_names.VALKYRIE_ENHANCED_CLUSTER_LAUNCHERS,
        item_names.VALKYRIE_FLECHETTE_MISSILES,
        item_names.VALKYRIE_LAUNCHING_VECTOR_COMPENSATOR,
        item_names.VALKYRIE_RESOURCE_EFFICIENCY,
        item_names.VALKYRIE_SHAPED_HULL,
    ]),
    Upgradeable(item_names.RAVEN, [
        item_names.RAVEN_ANTI_ARMOR_MISSILE,
        item_names.RAVEN_BIO_MECHANICAL_REPAIR_DRONE,
        item_names.RAVEN_DURABLE_MATERIALS,
        item_names.RAVEN_HUNTER_SEEKER_WEAPON,
        item_names.RAVEN_INTERFERENCE_MATRIX,
        item_names.RAVEN_INTERNAL_TECH_MODULE,
        item_names.RAVEN_RAILGUN_TURRET,
        item_names.RAVEN_RESOURCE_EFFICIENCY,
        item_names.RAVEN_SPIDER_MINES,
    ]),
    Upgradeable(item_names.SCIENCE_VESSEL, [
        item_names.SCIENCE_VESSEL_DEFENSIVE_MATRIX,
        item_names.SCIENCE_VESSEL_EMP_SHOCKWAVE,
        item_names.SCIENCE_VESSEL_IMPROVED_NANO_REPAIR,
        item_names.SCIENCE_VESSEL_MAGELLAN_COMPUTATION_SYSTEMS,
        item_names.SCIENCE_VESSEL_TACTICAL_JUMP,
    ]),
    Upgradeable(item_names.HERCULES, [
        item_names.HERCULES_INTERNAL_FUSION_MODULE,
        item_names.HERCULES_TACTICAL_JUMP,
    ]),
    Upgradeable(item_names.BATTLECRUISER, [
        item_names.BATTLECRUISER_ATX_LASER_BATTERY,
        item_names.BATTLECRUISER_BEHEMOTH_PLATING,
        item_names.BATTLECRUISER_BEHEMOTH_REACTOR,
        item_names.BATTLECRUISER_CLOAK,
        item_names.BATTLECRUISER_FIELD_ASSIST_TARGETING_SYSTEM,
        item_names.BATTLECRUISER_INTERNAL_TECH_MODULE,
        item_names.BATTLECRUISER_MOIRAI_IMPULSE_DRIVE,
        item_names.BATTLECRUISER_OPTIMIZED_LOGISTICS,
        item_names.BATTLECRUISER_PROGRESSIVE_DEFENSIVE_MATRIX,
        item_names.BATTLECRUISER_PROGRESSIVE_MISSILE_PODS,
        item_names.BATTLECRUISER_TACTICAL_JUMP,
    ]),
    SubSection("Buildings"),
    Upgradeable(item_names.BUNKER, [
        item_names.BUNKER_FORTIFIED_BUNKER,
        item_names.BUNKER_NEOSTEEL_BUNKER,
        item_names.BUNKER_PROJECTILE_ACCELERATOR,
        item_names.BUNKER_SHRIKE_TURRET,
    ]),
    Upgradeable(item_names.MISSILE_TURRET, [
        item_names.MISSILE_TURRET_HELLSTORM_BATTERIES,
        item_names.MISSILE_TURRET_RESOURCE_EFFICENCY,
        item_names.MISSILE_TURRET_TITANIUM_HOUSING,
    ]),
    Upgradeable(item_names.SENSOR_TOWER, [
        item_names.SENSOR_TOWER_ASSISTIVE_TARGETING,
        item_names.SENSOR_TOWER_MUILTISPECTRUM_DOPPLER,
    ]),
    Upgradeable(item_names.DEVASTATOR_TURRET, [
        item_names.DEVASTATOR_TURRET_ANTI_ARMOR_MUNITIONS,
        item_names.DEVASTATOR_TURRET_CONCUSSIVE_GRENADES,
        item_names.DEVASTATOR_TURRET_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.PLANETARY_FORTRESS, [
        item_names.PLANETARY_FORTRESS_IBIKS_TRACKING_SCANNERS,
        item_names.PLANETARY_FORTRESS_ORBITAL_MODULE,
        item_names.PLANETARY_FORTRESS_PROGRESSIVE_AUGMENTED_THRUSTERS,
    ]),
    Upgradeable(item_names.PERDITION_TURRET),
    Upgradeable(None, [
        item_names.HIVE_MIND_EMULATOR,
        item_names.ARGUS_AMPLIFIER,
        item_names.PSI_INDOCTRINATOR,
    ], classname="hive-mind-emulator"),
    Upgradeable(None, [
        item_names.PSI_DISRUPTER,
        item_names.SONIC_DISRUPTER,
        item_names.PSI_SCREEN,
    ], classname="psi-disrupter"),
    SubSection("Mercenaries"),
    Upgradeable(None, [
        item_names.WAR_PIGS,
        item_names.DEVIL_DOGS,
        item_names.HAMMER_SECURITIES,
        item_names.SPARTAN_COMPANY,
        item_names.SIEGE_BREAKERS,
        item_names.HELS_ANGELS,
        item_names.DUSK_WINGS,
        item_names.JACKSONS_REVENGE,
        item_names.SKIBIS_ANGELS,
        item_names.DEATH_HEADS,
        item_names.WINGED_NIGHTMARES,
        item_names.MIDNIGHT_RIDERS,
        item_names.BRYNHILDS,
        item_names.JOTUN,
    ], classname="terran-mercenary"),
    Upgradeable(None, [
        item_names.ROGUE_FORCES,
        item_names.RAPID_REINFORCEMENT,
        item_names.SIGNAL_BEACON,
        item_names.PROGRESSIVE_FAST_DELIVERY,
    ], classname="terran-mercenary-upgrade"),
    # SectionBreak("terran-royal-guard"),
    # Royal Guard
    Upgradeable(item_names.SON_OF_KORHAL),
    Upgradeable(item_names.FIELD_RESPONSE_THETA),
    Upgradeable(item_names.AEGIS_GUARD),
    Upgradeable(item_names.EMPERORS_SHADOW, [
        item_names.EMPERORS_SHADOW_SOVEREIGN_TACTICAL_MISSILES,
    ]),
    Upgradeable(item_names.BULWARK_COMPANY),
    Upgradeable(item_names.SHOCK_DIVISION),
    Upgradeable(item_names.BLACKHAMMER),
    Upgradeable(item_names.NIGHT_HAWK),
    Upgradeable(item_names.NIGHT_WOLF),
    Upgradeable(item_names.EMPERORS_GUARDIAN),
    Upgradeable(item_names.SKY_FURY),
    Upgradeable(item_names.PRIDE_OF_AUGUSTRGRAD),

    # SectionBreak("terran-macro"),
    SubSection("Miscellaneous"),
    Upgradeable((
        item_names.PROGRESSIVE_TERRAN_INFANTRY_WEAPON,
        item_names.PROGRESSIVE_TERRAN_INFANTRY_ARMOR,
        item_names.PROGRESSIVE_TERRAN_VEHICLE_WEAPON,
        item_names.PROGRESSIVE_TERRAN_VEHICLE_ARMOR,
        item_names.PROGRESSIVE_TERRAN_SHIP_WEAPON,
        item_names.PROGRESSIVE_TERRAN_SHIP_ARMOR,
    ), classname="terran-wa"),
    Upgradeable(None, [
        item_names.SCV_ADVANCED_CONSTRUCTION,
        item_names.SCV_DUAL_FUSION_WELDERS,
        item_names.SCV_HOSTILE_ENVIRONMENT_ADAPTATION,
        item_names.SCV_CONSTRUCTION_JUMP_JETS,
    ], classname="scv"),
    Upgradeable(None, [
        item_names.SPIDER_MINE_HIGH_EXPLOSIVE_MUNITION,
        item_names.SPIDER_MINE_CERBERUS_MINE,
    ], classname="spider-mine"),
    Upgradeable(None, [
        item_names.COMMAND_CENTER_SCANNER_SWEEP,
        item_names.COMMAND_CENTER_MULE,
        item_names.COMMAND_CENTER_EXTRA_SUPPLIES,
        item_names.COMMAND_CENTER_COMMAND_CENTER_REACTOR,
        # item_names.PROGRESSIVE_ORBITAL_COMMAND,
    ], classname="command-center"),
    Upgradeable(None, [
        item_names.PROGRESSIVE_FIRE_SUPPRESSION_SYSTEM,
        item_names.ULTRA_CAPACITORS,
        item_names.VANADIUM_PLATING,
        item_names.ORBITAL_DEPOTS,
        item_names.MICRO_FILTERING,
        item_names.AUTOMATED_REFINERY,
        item_names.TECH_REACTOR,
        item_names.ORBITAL_STRIKE,
        item_names.CELLULAR_REACTOR,
        item_names.PROGRESSIVE_REGENERATIVE_BIO_STEEL,
        item_names.STRUCTURE_ARMOR,
        item_names.HI_SEC_AUTO_TRACKING,
        item_names.ADVANCED_OPTICS,
        item_names.MECHANICAL_KNOW_HOW,
        item_names.MERCENARY_MUNITIONS,
        item_names.FUSION_CORE_FUSION_REACTOR,
    ], classname="terran-macro"),
]

ZERG_ITEMS: list[TrackerElements] = [
    SubSection("Ground"),
    Upgradeable(item_names.ZERGLING, [
        item_names.ZERGLING_ADRENAL_OVERLOAD,
        item_names.ZERGLING_HARDENED_CARAPACE,
        item_names.ZERGLING_METABOLIC_BOOST,
        item_names.ZERGLING_RAPTOR_STRAIN,
        item_names.ZERGLING_RECONSTITUTION,
        item_names.ZERGLING_SHREDDING_CLAWS,
        item_names.ZERGLING_SWARMLING_STRAIN,
    ]),
    Upgradeable(item_names.SWARM_QUEEN, [
        item_names.SWARM_QUEEN_BIO_MECHANICAL_TRANSFUSION,
        item_names.SWARM_QUEEN_DEEP_TUNNEL,
        item_names.SWARM_QUEEN_INCUBATOR_CHAMBER,
        item_names.SWARM_QUEEN_ORGANIC_CARAPACE,
        item_names.SWARM_QUEEN_RESOURCE_EFFICIENCY,
        item_names.SWARM_QUEEN_SPAWN_LARVAE,
    ]),
    Upgradeable(item_names.ROACH, [
        item_names.ROACH_ADAPTIVE_PLATING,
        item_names.ROACH_CORPSER_STRAIN,
        item_names.ROACH_GLIAL_RECONSTITUTION,
        item_names.ROACH_HYDRIODIC_BILE,
        item_names.ROACH_ORGANIC_CARAPACE,
        item_names.ROACH_TUNNELING_CLAWS,
        item_names.ROACH_VILE_STRAIN,
    ]),
    Upgradeable(item_names.HYDRALISK, [
        item_names.HYDRALISK_ANCILLARY_CARAPACE,
        item_names.HYDRALISK_FRENZY,
        item_names.HYDRALISK_GROOVED_SPINES,
        item_names.HYDRALISK_MUSCULAR_AUGMENTS,
        item_names.HYDRALISK_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.ABERRATION, [
        item_names.ABERRATION_BANELING_INCUBATION,
        item_names.ABERRATION_CONSTRUCT_REGENERATION,
        item_names.ABERRATION_MONSTROUS_RESILIENCE,
        item_names.ABERRATION_PROGRESSIVE_BANELING_LAUNCH,
        item_names.ABERRATION_PROTECTIVE_COVER,
        item_names.ABERRATION_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.SWARM_HOST, [
        item_names.SWARM_HOST_BURROW,
        item_names.SWARM_HOST_CARRION_STRAIN,
        item_names.SWARM_HOST_CREEPER_STRAIN,
        item_names.SWARM_HOST_ENDURING_LOCUSTS,
        item_names.SWARM_HOST_LOCUST_METABOLIC_BOOST,
        item_names.SWARM_HOST_ORGANIC_CARAPACE,
        item_names.SWARM_HOST_PRESSURIZED_GLANDS,
        item_names.SWARM_HOST_RAPID_INCUBATION,
        item_names.SWARM_HOST_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.INFESTOR, [
        item_names.INFESTOR_INFESTED_TERRAN,
        item_names.INFESTOR_MICROBIAL_SHROUD,
    ]),
    Upgradeable(item_names.ULTRALISK, [
        item_names.ULTRALISK_ANABOLIC_SYNTHESIS,
        item_names.ULTRALISK_BURROW_CHARGE,
        item_names.ULTRALISK_CHITINOUS_PLATING,
        item_names.ULTRALISK_MONARCH_BLADES,
        item_names.ULTRALISK_NOXIOUS_STRAIN,
        item_names.ULTRALISK_ORGANIC_CARAPACE,
        item_names.ULTRALISK_RESOURCE_EFFICIENCY,
        item_names.ULTRALISK_TISSUE_ASSIMILATION,
        item_names.ULTRALISK_TORRASQUE_STRAIN,
    ]),
    Upgradeable(item_names.DEFILER, [
        item_names.DEFILER_COMORBIDITY,
        item_names.DEFILER_PATHOGEN_PROJECTORS,
        item_names.DEFILER_PREDATORY_CONSUMPTION,
        item_names.DEFILER_TRAPDOOR_ADAPTATION,
    ]),
    Upgradeable(item_names.PYGALISK, [
        item_names.PYGALISK_COMBAT_CARAPACE,
        item_names.PYGALISK_DUCAL_BLADES,
        item_names.PYGALISK_STIM,
    ]),
    SubSection("Flyers"),
    Upgradeable(item_names.MUTALISK, [
        item_names.MUTALISK_AERODYNAMIC_GLAIVE_SHAPE,
        item_names.MUTALISK_RAPID_REGENERATION,
        item_names.MUTALISK_SEVERING_GLAIVE,
        item_names.MUTALISK_SUNDERING_GLAIVE,
        item_names.MUTALISK_VICIOUS_GLAIVE,
    ]),
    Upgradeable(item_names.CORRUPTOR, [
        item_names.CORRUPTOR_CAUSTIC_SPRAY,
        item_names.CORRUPTOR_CONSTRUCT_REGENERATION,
        item_names.CORRUPTOR_CORRUPTION,
        item_names.CORRUPTOR_MONSTROUS_RESILIENCE,
        item_names.CORRUPTOR_RESOURCE_EFFICIENCY,
        item_names.CORRUPTOR_SCOURGE_INCUBATION,
    ]),
    Upgradeable(item_names.SCOURGE, [
        item_names.SCOURGE_RESOURCE_EFFICIENCY,
        item_names.SCOURGE_SWARM_SCOURGE,
        item_names.SCOURGE_VIRULENT_SPORES,
    ]),
    Upgradeable(item_names.BROOD_QUEEN, [
        item_names.BROOD_QUEEN_ENHANCED_MITOCHONDRIA,
        item_names.BROOD_QUEEN_ENSNARE,
        item_names.BROOD_QUEEN_FUNGAL_GROWTH,
    ]),
    SubSection("Morphs"),
    Upgradeable(item_names.ZERGLING_BANELING_ASPECT, [
        item_names.BANELING_CENTRIFUGAL_HOOKS,
        item_names.BANELING_CORROSIVE_ACID,
        item_names.BANELING_HUNTER_STRAIN,
        item_names.BANELING_RAPID_METAMORPH,
        item_names.BANELING_REGENERATIVE_ACID,
        item_names.BANELING_RUPTURE,
        item_names.BANELING_SPLITTER_STRAIN,
        item_names.BANELING_TUNNELING_JAWS,
    ]),
    Upgradeable(item_names.HYDRALISK_IMPALER_ASPECT, [
        item_names.IMPALER_ADAPTIVE_TALONS,
        item_names.IMPALER_SECRETION_GLANDS,
        item_names.IMPALER_SUNKEN_SPINES,
    ]),
    Upgradeable(item_names.HYDRALISK_LURKER_ASPECT, [
        item_names.LURKER_ADAPTED_SPINES,
        item_names.LURKER_SEISMIC_SPINES,
    ]),
    Upgradeable(item_names.MUTALISK_CORRUPTOR_BROOD_LORD_ASPECT, [
        item_names.BROOD_LORD_BEHEMOTH_STELLARSKIN,
        item_names.BROOD_LORD_POROUS_CARTILAGE,
        item_names.BROOD_LORD_RESOURCE_EFFICIENCY,
        item_names.BROOD_LORD_SPLITTER_MITOSIS,
    ]),
    Upgradeable(item_names.MUTALISK_CORRUPTOR_VIPER_ASPECT, [
        item_names.VIPER_PARALYTIC_BARBS,
        item_names.VIPER_PARASITIC_BOMB,
        item_names.VIPER_VIRULENT_MICROBES,
    ]),
    Upgradeable(item_names.MUTALISK_CORRUPTOR_GUARDIAN_ASPECT, [
        item_names.GUARDIAN_EXPLOSIVE_SPORES,
        item_names.GUARDIAN_PRIMAL_ADAPTATION,
        item_names.GUARDIAN_PRIMORDIAL_FURY,
        item_names.GUARDIAN_PROLONGED_DISPERSION,
        item_names.GUARDIAN_PROPELLANT_SACS,
        item_names.GUARDIAN_SORONAN_ACID,
    ]),
    Upgradeable(item_names.MUTALISK_CORRUPTOR_DEVOURER_ASPECT, [
        item_names.DEVOURER_CORROSIVE_SPRAY,
        item_names.DEVOURER_GAPING_MAW,
        item_names.DEVOURER_IMPROVED_OSMOSIS,
        item_names.DEVOURER_PRESCIENT_SPORES,
    ]),
    Upgradeable(item_names.ROACH_RAVAGER_ASPECT, [
        item_names.RAVAGER_BLOATED_BILE_DUCTS,
        item_names.RAVAGER_DEEP_TUNNEL,
        item_names.RAVAGER_POTENT_BILE,
    ]),
    Upgradeable(item_names.OVERLORD_OVERSEER_ASPECT),
    Upgradeable(item_names.ROACH_PRIMAL_IGNITER_ASPECT, [
        item_names.PRIMAL_IGNITER_CONCENTRATED_FIRE,
        item_names.PRIMAL_IGNITER_PRIMAL_TENACITY,
    ]),
    Upgradeable(item_names.ULTRALISK_TYRANNOZOR_ASPECT, [
        item_names.TYRANNOZOR_BARRAGE_OF_SPIKES,
        item_names.TYRANNOZOR_HEALING_ADAPTATION,
        item_names.TYRANNOZOR_IMPALING_STRIKE,
        item_names.TYRANNOZOR_TYRANTS_PROTECTION,
    ]),
    SubSection("Infested"),
    Upgradeable(item_names.INFESTED_MARINE, [
        item_names.INFESTED_MARINE_PLAGUED_MUNITIONS,
        item_names.INFESTED_MARINE_RETINAL_AUGMENTATION,
    ]),
    Upgradeable(item_names.INFESTED_DIAMONDBACK, [
        item_names.INFESTED_DIAMONDBACK_CAUSTIC_MUCUS,
        item_names.INFESTED_DIAMONDBACK_CONCENTRATED_SPEW,
        item_names.INFESTED_DIAMONDBACK_PROGRESSIVE_FUNGAL_SNARE,
        item_names.INFESTED_DIAMONDBACK_VIOLENT_ENZYMES,
        item_names.INFESTED_DIAMONDBACK_FRIGHTFUL_FLESHWELDER,
    ]),
    Upgradeable(item_names.INFESTED_SIEGE_TANK, [
        item_names.INFESTED_SIEGE_TANK_ACIDIC_ENZYMES,
        item_names.INFESTED_SIEGE_TANK_BALANCED_ROOTS,
        item_names.INFESTED_SIEGE_TANK_DEEP_TUNNEL,
        item_names.INFESTED_SIEGE_TANK_PROGRESSIVE_AUTOMATED_MITOSIS,
        item_names.INFESTED_SIEGE_TANK_SEISMIC_SONAR,
        item_names.INFESTED_SIEGE_TANK_FRIGHTFUL_FLESHWELDER,
    ]),
    Upgradeable(item_names.INFESTED_BANSHEE, [
        item_names.INFESTED_BANSHEE_BRACED_EXOSKELETON,
        item_names.INFESTED_BANSHEE_FLESHFUSED_TARGETING_OPTICS,
        item_names.INFESTED_BANSHEE_RAPID_HIBERNATION,
        item_names.INFESTED_BANSHEE_FRIGHTFUL_FLESHWELDER,
    ]),
    Upgradeable(item_names.INFESTED_LIBERATOR, [
        item_names.INFESTED_LIBERATOR_CLOUD_DISPERSAL,
        item_names.INFESTED_LIBERATOR_DEFENDER_MODE,
        item_names.INFESTED_LIBERATOR_VIRAL_CONTAMINATION,
        item_names.INFESTED_LIBERATOR_FRIGHTFUL_FLESHWELDER,
    ]),
    Upgradeable(item_names.BULLFROG, [
        item_names.BULLFROG_BROODLINGS,
        item_names.BULLFROG_HARD_IMPACT,
        item_names.BULLFROG_RANGE,
        item_names.BULLFROG_WILD_MUTATION,
    ]),
    SubSection("Buildings"),
    Upgradeable(item_names.SPINE_CRAWLER),
    Upgradeable(item_names.SPORE_CRAWLER, [
        item_names.SPORE_CRAWLER_BIO_BONUS,
    ]),
    Upgradeable(item_names.BILE_LAUNCHER, [
        item_names.BILE_LAUNCHER_ARTILLERY_DUCTS,
        item_names.BILE_LAUNCHER_RAPID_BOMBARMENT,
    ]),
    Upgradeable(item_names.INFESTED_BUNKER, [
        item_names.INFESTED_BUNKER_CALCIFIED_ARMOR,
        item_names.INFESTED_BUNKER_ENGORGED_BUNKERS,
        item_names.INFESTED_BUNKER_REGENERATIVE_PLATING,
    ]),
    Upgradeable(item_names.INFESTED_MISSILE_TURRET, [
        item_names.INFESTED_MISSILE_TURRET_ACID_SPORE_VENTS,
        item_names.INFESTED_MISSILE_TURRET_BIOELECTRIC_PAYLOAD,
    ]),
    Upgradeable(item_names.NYDUS_WORM, [
        item_names.NYDUS_WORM_RAVENOUS_APPETITE,
    ]),
    Upgradeable(item_names.ECHIDNA_WORM, [
        item_names.ECHIDNA_WORM_OUROBOROS_STRAIN,
    ]),
    Upgradeable(Spacer(), [
        item_names.NYDUS_WORM_ECHIDNA_WORM_JORMUNGANDR_STRAIN,
        item_names.NYDUS_WORM_ECHIDNA_WORM_RESOURCE_EFFICIENCY,
        item_names.NYDUS_WORM_ECHIDNA_WORM_SUBTERRANEAN_SCALES,
    ], classname="zerg-worm"),
    SubSection("Mercenaries"),
    Upgradeable(None, [
        item_names.INFESTED_MEDICS,
        item_names.INFESTED_SIEGE_BREAKERS,
        item_names.INFESTED_DUSK_WINGS,
        item_names.DEVOURING_ONES,
        item_names.HUNTER_KILLERS,
        item_names.TORRASQUE_MERC,
        item_names.HUNTERLING,
        item_names.YGGDRASIL,
        item_names.CAUSTIC_HORRORS,
    ], classname="zerg-mercenary"),
    Upgradeable(None, [
        item_names.SELF_SUFFICIENT,
        item_names.UNRESTRICTED_MUTATION,
        item_names.EVOLUTIONARY_LEAP,
        item_names.CELL_DIVISION,
    ], classname="zerg-mercenary-upgrade"),

    # SectionBreak("zerg-macro"),
    SubSection("Miscellaneous"),
    Upgradeable((
        item_names.PROGRESSIVE_ZERG_MELEE_ATTACK,
        item_names.PROGRESSIVE_ZERG_MISSILE_ATTACK,
        item_names.PROGRESSIVE_ZERG_GROUND_CARAPACE,
        item_names.PROGRESSIVE_ZERG_FLYER_ATTACK,
        item_names.PROGRESSIVE_ZERG_FLYER_CARAPACE,
    ), classname="zerg-wa"),
    Upgradeable(None, [
        item_names.OVERLORD_IMPROVED_OVERLORDS,
        item_names.OVERLORD_VENTRAL_SACS,
        item_names.OVERLORD_GENERATE_CREEP,
        item_names.OVERLORD_ANTENNAE,
        item_names.OVERLORD_PNEUMATIZED_CARAPACE,
    ], classname="overlord"),
    Upgradeable(None, (
        item_names.INFESTED_SCV_BUILD_CHARGES,
        item_names.TWIN_DRONES,
        item_names.AUTOMATED_EXTRACTORS,
        item_names.MALIGNANT_CREEP,
        item_names.VESPENE_EFFICIENCY,
        item_names.ZERG_EXCAVATING_CLAWS,
        item_names.ZERG_CREEP_STOMACH,
        item_names.HIVE_CLUSTER_MATURATION,
        item_names.MACROSCOPIC_RECUPERATION,
        item_names.BIOMECHANICAL_STOCKPILING,
        item_names.BROODLING_SPORE_SATURATION,
    ), classname="zerg-macro"),
]

PROTOSS_ITEMS: list[TrackerElements] = [
    SubSection("Gateway"),
    Upgradeable(item_names.ZEALOT, [
        item_names.ZEALOT_WHIRLWIND,
    ]),
    Upgradeable(item_names.CENTURION, [
        item_names.CENTURION_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.SENTINEL, [
        item_names.SENTINEL_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(Spacer(), [
        item_names.ZEALOT_SENTINEL_CENTURION_LEG_ENHANCEMENTS,
        item_names.ZEALOT_SENTINEL_CENTURION_SHIELD_CAPACITY,
    ], classname="zealot-tier"),
    Upgradeable(item_names.SUPPLICANT, [
        item_names.SUPPLICANT_BLOOD_SHIELD,
        item_names.SUPPLICANT_ENDLESS_SERVITUDE,
        item_names.SUPPLICANT_SACRIFICE,
        item_names.SUPPLICANT_SOUL_AUGMENTATION,
        item_names.SUPPLICANT_ZENITH_PITCH,
    ]),
    Upgradeable(item_names.STALKER, [
        item_names.STALKER_PHASE_REACTOR,
    ]),
    Upgradeable(item_names.INSTIGATOR, [
        item_names.INSTIGATOR_BLINK_OVERDRIVE,
        item_names.INSTIGATOR_MODERNIZED_SERVOS,
        item_names.INSTIGATOR_RECONSTRUCTION,
    ]),
    Upgradeable(item_names.SLAYER, [
        item_names.SLAYER_PHASE_BLINK,
    ]),
    Upgradeable(Spacer(), [
        item_names.STALKER_INSTIGATOR_SLAYER_DISINTEGRATING_PARTICLES,
        item_names.STALKER_INSTIGATOR_SLAYER_PARTICLE_REFLECTION,
    ], classname="stalker-tier"),
    Upgradeable(item_names.SENTRY, [
        item_names.SENTRY_DOUBLE_SHIELD_RECHARGE,
        item_names.SENTRY_FORCE_FIELD,
        item_names.SENTRY_HALLUCINATION,
    ]),
    Upgradeable(item_names.ENERGIZER, [
        item_names.ENERGIZER_FORGED_CHASSIS,
        item_names.ENERGIZER_MOBILE_CHRONO_BEAM,
        item_names.ENERGIZER_RECLAMATION,
    ]),
    Upgradeable(item_names.HAVOC, [
        item_names.HAVOC_BLOODSHARD_RESONANCE,
        item_names.HAVOC_DETECT_WEAKNESS,
        item_names.HAVOC_ENDURING_SIGHT,
    ]),
    Upgradeable(Spacer(), [
        item_names.SENTRY_ENERGIZER_HAVOC_CLOAKING_MODULE,
        item_names.SENTRY_ENERGIZER_HAVOC_SHIELD_BATTERY_RAPID_RECHARGING,
    ], classname="sentry-tier"),
    Upgradeable(item_names.DRAGOON, [
        item_names.DRAGOON_CONCENTRATED_ANTIMATTER,
        item_names.DRAGOON_ENHANCED_STRIDER_SERVOS,
        item_names.DRAGOON_PHALANX_SUIT,
        item_names.DRAGOON_SINGULARITY_CHARGE,
        item_names.DRAGOON_TRILLIC_COMPRESSION_SYSTEM,
    ]),
    Upgradeable(item_names.ADEPT, [
        item_names.ADEPT_DISRUPTIVE_TRANSFER,
        item_names.ADEPT_PHASE_BULWARK,
        item_names.ADEPT_RESONATING_GLAIVES,
        item_names.ADEPT_SHOCKWAVE,
    ]),
    Upgradeable(item_names.HIGH_TEMPLAR, [
        item_names.HIGH_TEMPLAR_PLASMA_SURGE,
    ]),
    Upgradeable(item_names.SIGNIFIER, [
        item_names.SIGNIFIER_FEEDBACK,
    ]),
    Upgradeable(item_names.ASCENDANT, [
        item_names.ASCENDANT_ARCHON_MERGE,
        item_names.ASCENDANT_BLOOD_AMULET,
        item_names.ASCENDANT_BREATH_OF_CREATION,
        item_names.ASCENDANT_CHAOTIC_ATTUNEMENT,
        item_names.ASCENDANT_POWER_OVERWHELMING,
    ]),
    Upgradeable(Spacer(), [
        item_names.HIGH_TEMPLAR_SIGNIFIER_HALLUCINATION,
        item_names.HIGH_TEMPLAR_SIGNIFIER_KHAYDARIN_AMULET,
        item_names.HIGH_TEMPLAR_SIGNIFIER_UNSHACKLED_PSIONIC_STORM,
    ], classname="high-templar-tier"),
    Upgradeable(Spacer(), [
        item_names.ARCHON_HIGH_ARCHON,
        item_names.ARCHON_TRANSCENDENCE,
        item_names.ARCHON_POWER_SIPHON,
        item_names.ARCHON_ERADICATE,
        item_names.ARCHON_OBLITERATE,
    ], classname="archon"),
    Upgradeable(item_names.DARK_ARCHON, [
        item_names.DARK_ARCHON_ARGUS_TALISMAN,
        item_names.DARK_ARCHON_FEEDBACK,
        item_names.DARK_ARCHON_INDOMITABLE_WILL,
        item_names.DARK_ARCHON_MAELSTROM,
    ]),
    Upgradeable(item_names.DARK_TEMPLAR, [
        item_names.DARK_TEMPLAR_ARCHON_MERGE,
        item_names.DARK_TEMPLAR_DARK_ARCHON_MELD,
        item_names.DARK_TEMPLAR_GREATER_SHADOW_FURY,
        item_names.DARK_TEMPLAR_LESSER_SHADOW_FURY,
    ]),
    Upgradeable(item_names.AVENGER, [
        item_names.AVENGER_KRYHAS_CLOAK,
    ]),
    Upgradeable(item_names.BLOOD_HUNTER, [
        item_names.BLOOD_HUNTER_BRUTAL_EFFICIENCY,
    ]),
    Upgradeable(Spacer(), [
        item_names.DARK_TEMPLAR_AVENGER_BLOOD_HUNTER_BLINK,
        item_names.DARK_TEMPLAR_AVENGER_BLOOD_HUNTER_RESOURCE_EFFICIENCY,
        item_names.DARK_TEMPLAR_AVENGER_BLOOD_HUNTER_SHADOW_GUARD_TRAINING,
        item_names.DARK_TEMPLAR_AVENGER_BLOOD_HUNTER_SHROUD_OF_ADUN,
    ], classname="dark-templar-tier"),
    SubSection("Robotics Facility"),
    Upgradeable(item_names.IMMORTAL, [
        item_names.IMMORTAL_IMPROVED_BARRIER,
    ]),
    Upgradeable(item_names.ANNIHILATOR, [
        item_names.ANNIHILATOR_TWILIGHT_CHASSIS,
    ]),
    Upgradeable(Spacer(), [
        item_names.IMMORTAL_ANNIHILATOR_ADVANCED_TARGETING,
        item_names.IMMORTAL_ANNIHILATOR_DISRUPTOR_DISPERSION,
        item_names.IMMORTAL_ANNIHILATOR_SINGULARITY_CHARGE,
    ], classname="immortal-tier"),
    Upgradeable(item_names.VANGUARD, [
        item_names.VANGUARD_AGONY_LAUNCHERS,
        item_names.VANGUARD_FUSION_MORTARS,
        item_names.VANGUARD_MATTER_DISPERSION,
        item_names.VANGUARD_RAPIDFIRE_CANNON,
    ]),
    Upgradeable(item_names.STALWART, [
        item_names.STALWART_ARC_INDUCERS,
        item_names.STALWART_HIGH_VOLTAGE_CAPACITORS,
        item_names.STALWART_LATTICED_SHIELDING,
        item_names.STALWART_REINTEGRATED_FRAMEWORK,
        item_names.STALWART_STABILIZED_ELECTRODES,
    ]),
    Upgradeable(item_names.COLOSSUS, [
        item_names.COLOSSUS_FIRE_LANCE,
        item_names.COLOSSUS_PACIFICATION_PROTOCOL,
    ]),
    Upgradeable(item_names.WRATHWALKER, [
        item_names.WRATHWALKER_AERIAL_TRACKING,
        item_names.WRATHWALKER_EYE_OF_WRATH,
        item_names.WRATHWALKER_RAPID_POWER_CYCLING,
    ]),
    Upgradeable(item_names.REAVER, [
        item_names.REAVER_BARGAIN_BIN_PRICES,
        item_names.REAVER_KHALAI_REPLICATORS,
        item_names.REAVER_REAVER_CAPACITY,
        item_names.REAVER_RESOURCE_EFFICIENCY,
        item_names.REAVER_SCARAB_DAMAGE,
        item_names.REAVER_SOLARITE_PAYLOAD,
    ]),
    Upgradeable(item_names.DISRUPTOR, [
        item_names.DISRUPTOR_CLOAKING_MODULE,
        item_names.DISRUPTOR_MOBILITY_PROTOCOLS,
        item_names.DISRUPTOR_PERFECTED_POWER,
        item_names.DISRUPTOR_RESTRAINED_DESTRUCTION,
    ]),
    Upgradeable(item_names.OBSERVER, [
        item_names.OBSERVER_GRAVITIC_BOOSTERS,
        item_names.OBSERVER_INDUCE_SCOPOPHOBIA,
        item_names.OBSERVER_SENSOR_ARRAY,
    ]),
    Upgradeable(item_names.WARP_PRISM, [
        item_names.WARP_PRISM_GRAVITIC_DRIVE,
        item_names.WARP_PRISM_PHASE_BLASTER,
        item_names.WARP_PRISM_WARP_REFRACTION,
        item_names.WARP_PRISM_WAR_CONFIGURATION,
    ]),
    SubSection("Stargate"),
    Upgradeable(item_names.PHOENIX, [
        item_names.PHOENIX_DOUBLE_GRAVITON_BEAM,
    ]),
    Upgradeable(item_names.MIRAGE, [
        item_names.MIRAGE_GRAVITON_BEAM,
    ]),
    Upgradeable(item_names.SKIRMISHER, [
        item_names.SKIRMISHER_PEER_CONTEMPT,
    ]),
    Upgradeable(Spacer(), [
        item_names.PHOENIX_CLASS_ANION_PULSE_CRYSTALS,
        item_names.PHOENIX_CLASS_IONIC_WAVELENGTH_FLUX,
    ], classname="phoenix-tier"),
    Upgradeable(item_names.CORSAIR, [
        item_names.CORSAIR_ARGUS_JEWEL,
        item_names.CORSAIR_NETWORK_DISRUPTION,
        item_names.CORSAIR_NEUTRON_SHIELDS,
        item_names.CORSAIR_STEALTH_DRIVE,
        item_names.CORSAIR_SUSTAINING_DISRUPTION,
    ]),
    Upgradeable(item_names.VOID_RAY, [
        item_names.VOID_RAY_PRISMATIC_RANGE,
    ]),
    Upgradeable(item_names.DESTROYER, [
        item_names.DESTROYER_REFORGED_BLOODSHARD_CORE,
        item_names.DESTROYER_RESOURCE_EFFICIENCY,
    ]),
    Upgradeable(item_names.PULSAR, [
        item_names.PULSAR_CHRONOCLYSM,
        item_names.PULSAR_CHRONO_SHEAR,
        item_names.PULSAR_ENTROPIC_REVERSAL,
    ]),
    Upgradeable(item_names.DAWNBRINGER, [
        item_names.DAWNBRINGER_ANTI_SURFACE_COUNTERMEASURES,
        item_names.DAWNBRINGER_ENHANCED_SHIELD_GENERATOR,
        item_names.DAWNBRINGER_SOLARITE_LENS,
    ]),
    Upgradeable(Spacer(), [
        item_names.VOID_RAY_DESTROYER_PULSAR_DAWNBRINGER_FLUX_VANES,
    ], classname="void-ray-tier"),
    Upgradeable(item_names.SCOUT, [
        item_names.SCOUT_APIAL_SENSORS,
        item_names.SCOUT_EXPEDITIONARY_HULL,
        item_names.SCOUT_RESOURCE_EFFICIENCY,
        item_names.SCOUT_SUPPLY_EFFICIENCY,
    ]),
    Upgradeable(item_names.OPPRESSOR, [
        item_names.OPPRESSOR_ACCELERATED_WARP,
        item_names.OPPRESSOR_ARMOR_MELTING_BLASTERS,
        item_names.OPPRESSOR_VULCAN_BLASTER,
    ]),
    Upgradeable(item_names.CALADRIUS, [
        item_names.CALADRIUS_CORONA_BEAM,
        item_names.CALADRIUS_SIDE_MISSILES,
        item_names.CALADRIUS_SOLARITE_REACTOR,
        item_names.CALADRIUS_STRUCTURE_TARGETING,
    ]),
    Upgradeable(item_names.MISTWING, [
        item_names.MISTWING_NULL_SHROUD,
        item_names.MISTWING_PHANTOM_DASH,
        item_names.MISTWING_PILOT,
    ]),
    Upgradeable(Spacer(), [
        item_names.SCOUT_ADVANCED_PHOTON_BLASTERS,
        item_names.SCOUT_COMBAT_SENSOR_ARRAY,
        item_names.SCOUT_GRAVITIC_THRUSTERS,
    ], classname="scout-tier"),
    Upgradeable(item_names.CARRIER, [
        item_names.CARRIER_REPAIR_DRONES,
    ]),
    Upgradeable(item_names.TRIREME, [
        item_names.TRIREME_SOLAR_BEAM,
    ]),
    Upgradeable(item_names.SKYLORD, [
        item_names.SKYLORD_JUMP,
    ]),
    Upgradeable(Spacer(), [
        item_names.CARRIER_SKYLORD_TRIREME_HULL_OF_PAST_GLORIES,
        item_names.CARRIER_TRIREME_GRAVITON_CATAPULT,
    ], classname="carrier-tier"),
    Upgradeable(item_names.TEMPEST, [
        item_names.TEMPEST_DISINTEGRATION,
        item_names.TEMPEST_GRAVITY_SLING,
        item_names.TEMPEST_INTERPLANETARY_RANGE,
        item_names.TEMPEST_QUANTIC_REACTOR,
        item_names.TEMPEST_TECTONIC_DESTABILIZERS,
    ]),
    Upgradeable(item_names.ARBITER, [
        item_names.ARBITER_CHRONOSTATIC_REINFORCEMENT,
        item_names.ARBITER_JUDICATORS_VEIL,
        item_names.ARBITER_KHAYDARIN_CORE,
        item_names.ARBITER_RESOURCE_EFFICIENCY,
        item_names.ARBITER_SPACETIME_ANCHOR,
        item_names.ARBITER_VESSEL_OF_THE_CONCLAVE,
    ]),
    Upgradeable(item_names.ORACLE, [
        item_names.ORACLE_BOSONIC_CORE,
        item_names.ORACLE_SKYWARD_CHRONOANOMALY,
        item_names.ORACLE_STASIS_CALIBRATION,
        item_names.ORACLE_STEALTH_DRIVE,
        item_names.ORACLE_TEMPORAL_ACCELERATION_BEAM,
    ]),
    Upgradeable(item_names.MOTHERSHIP, [
        item_names.MOTHERSHIP_INTEGRATED_POWER,
    ]),
    SubSection("Buildings"),
    Upgradeable((
        item_names.PHOTON_CANNON,
        item_names.KHAYDARIN_MONOLITH,
        item_names.SHIELD_BATTERY,
    ), classname="protoss-static-defense"),
    Upgradeable(None, (
        item_names.NEXUS_OVERCHARGE,
        item_names.ENHANCED_TARGETING,
        item_names.OPTIMIZED_ORDNANCE,
    ), classname="protoss-static-defense-upgrade"),
    
    # SectionBreak("protoss-macro"),
    SubSection("Miscellaneous"),
    Upgradeable((
        item_names.PROGRESSIVE_PROTOSS_GROUND_WEAPON,
        item_names.PROGRESSIVE_PROTOSS_GROUND_ARMOR,
        item_names.PROGRESSIVE_PROTOSS_SHIELDS,
        item_names.PROGRESSIVE_PROTOSS_AIR_WEAPON,
        item_names.PROGRESSIVE_PROTOSS_AIR_ARMOR,
    ), classname="protoss-wa"),
    Upgradeable(None, (
        item_names.SOA_CHRONO_SURGE,
        item_names.SOA_PROGRESSIVE_PROXY_PYLON,
        item_names.SOA_PYLON_OVERCHARGE,
        item_names.SOA_ORBITAL_STRIKE,
        item_names.SOA_TEMPORAL_FIELD,
        item_names.SOA_SOLAR_LANCE,
        item_names.SOA_MASS_RECALL,
        item_names.SOA_SHIELD_OVERCHARGE,
        item_names.SOA_DEPLOY_FENIX,
        item_names.SOA_PURIFIER_BEAM,
        item_names.SOA_TIME_STOP,
        item_names.SOA_SOLAR_BOMBARDMENT,
    ), classname="soa"),
    Upgradeable(None, (
        item_names.GUARDIAN_SHELL,
        item_names.RECONSTRUCTION_BEAM,
        item_names.OVERWATCH,
    ), classname="soa"),
    Upgradeable(None, (
        item_names.MATRIX_OVERLOAD,
        item_names.QUATRO,
        item_names.ORBITAL_ASSIMILATORS,
        item_names.AMPLIFIED_ASSIMILATORS,
        item_names.WARP_HARMONIZATION,
        item_names.SUPERIOR_WARP_GATES,
        item_names.KHALAI_INGENUITY,
        item_names.PROGRESSIVE_WARP_RELOCATE,
        item_names.PROBE_WARPIN,
        item_names.ELDER_PROBES,
    ), classname="protoss-macro"),
]

NOVA_ITEMS = [
    Upgradeable((
        item_names.NOVA_C20A_CANISTER_RIFLE,
        item_names.NOVA_HELLFIRE_SHOTGUN,
        item_names.NOVA_PLASMA_RIFLE,
        item_names.NOVA_MONOMOLECULAR_BLADE,
        item_names.NOVA_BLAZEFIRE_GUNBLADE,
    ), classname="nova-weapons"),
    Upgradeable((
        item_names.NOVA_GHOST_VISOR,
        item_names.NOVA_RANGEFINDER_OCULUS,
        item_names.NOVA_DOMINATION,
    ), classname="nova-visors"),
    Upgradeable((
        item_names.NOVA_PULSE_GRENADES,
        item_names.NOVA_FLASHBANG_GRENADES,
        item_names.NOVA_STIM_INFUSION,
        item_names.NOVA_IONIC_FORCE_FIELD,
        item_names.NOVA_HOLO_DECOY,
    ), classname="nova-gadgets"),
    Upgradeable((
        item_names.NOVA_BLINK,
        item_names.NOVA_PROGRESSIVE_STEALTH_SUIT_MODULE,
        item_names.NOVA_ENERGY_SUIT_MODULE,
        item_names.NOVA_ARMORED_SUIT_MODULE,
        item_names.NOVA_JUMP_SUIT_MODULE,
    ), classname="nova-suits"),
    Upgradeable((item_names.NOVA_NUKE,), classname="nova-utility")
]

KERRIGAN_ITEMS = [
    FillerCounter("Kerrigan Level"),
    Upgradeable((
        item_names.KERRIGAN_KINETIC_BLAST,
        item_names.KERRIGAN_LEAPING_STRIKE,
        item_names.KERRIGAN_CRUSHING_GRIP,
        item_names.KERRIGAN_PSIONIC_SHIFT,
        item_names.KERRIGAN_WILD_MUTATION,
        item_names.KERRIGAN_SPAWN_BANELINGS,
        item_names.KERRIGAN_MEND,
        item_names.KERRIGAN_ASSIMILATION_AURA,
    ), classname="kerrigan-actives"),
    Upgradeable((
        item_names.KERRIGAN_HEROIC_FORTITUDE,
        item_names.KERRIGAN_CHAIN_REACTION,
        item_names.KERRIGAN_INFEST_BROODLINGS,
        item_names.KERRIGAN_FURY,
        item_names.KERRIGAN_ABILITY_EFFICIENCY,
    ), classname="kerrigan-passives"),
    Upgradeable((
        item_names.KERRIGAN_APOCALYPSE,
        item_names.KERRIGAN_SPAWN_LEVIATHAN,
        item_names.KERRIGAN_DROP_PODS,
        item_names.KERRIGAN_IMMOBILIZATION_WAVE,
    ), classname="kerrigan-ultimates"),
    Upgradeable((item_names.KERRIGAN_PRIMAL_FORM,), classname="kerrigan-form")
    # item_names.KERRIGAN_LEVELS_10,
    # item_names.KERRIGAN_LEVELS_9,
    # item_names.KERRIGAN_LEVELS_8,
    # item_names.KERRIGAN_LEVELS_7,
    # item_names.KERRIGAN_LEVELS_6,
    # item_names.KERRIGAN_LEVELS_5,
    # item_names.KERRIGAN_LEVELS_4,
    # item_names.KERRIGAN_LEVELS_3,
    # item_names.KERRIGAN_LEVELS_2,
    # item_names.KERRIGAN_LEVELS_1,
    # item_names.KERRIGAN_LEVELS_14,
    # item_names.KERRIGAN_LEVELS_35,
    # item_names.KERRIGAN_LEVELS_70,
]
